/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        "classpath" (group="org.jetbrains.kotlin", name="kotlin-gradle-plugin", version="1.5.30" )
        "classpath" (group="org.jetbrains.kotlin", name="kotlin-allopen", version="1.5.30" ) 
        "classpath" (group="org.springframework.boot", name="spring-boot-gradle-plugin", version="1.5.4.RELEASE")
    }
}

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    
    idea
  kotlin("plugin.jpa") version "1.4.32"
  id("org.springframework.boot") version "2.4.4"
  id("io.spring.dependency-management") version "1.0.11.RELEASE"
  kotlin("jvm") version "1.4.32"
  kotlin("plugin.spring") version "1.4.32"
}

sourceSets.main {
    java.srcDirs("src/main/kotlin")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
   
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-mustache")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Jackson Dependencies
    implementation ("com.fasterxml.jackson.core:jackson-annotations")
    implementation ("com.fasterxml.jackson.core:jackson-core")
    implementation ("com.fasterxml.jackson.core:jackson-databind")
    runtimeOnly ("com.fasterxml.jackson.datatype:jackson-datatype-jdk8")
    runtimeOnly ("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")
    runtimeOnly ("com.fasterxml.jackson.module:jackson-module-kotlin")

    runtimeOnly("com.h2database:h2")
    runtimeOnly("org.springframework.boot:spring-boot-devtools")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

tasks.withType<Wrapper> {
    gradleVersion = "3.5"
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
      freeCompilerArgs = listOf("-Xjsr305=strict")
      jvmTarget = "11"
  }
}